# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PirJJMHCe3UXjL9q5o7gSFX0floSk_f8
"""

list = ["1", "3", "2"]
print(list[0])

t=['a','b','c','d','e','f']
t[1:3]

t[4:]

t[:]

